# Generated by Django 3.1.5 on 2021-01-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortfood',
            name='mealtype',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('LU', 'Lunch'), ('DR', 'Dinner')], max_length=100),
        ),
    ]
