# Generated by Django 3.1.5 on 2021-02-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortfood',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
