# Generated by Django 3.1.5 on 2021-02-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0002_auto_20210128_1859'),
        ('sort', '0002_sortfood_description'),
    ]

    operations = [
    ]
