# Generated by Django 3.1.5 on 2021-02-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0003_merge_20210225_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortfood',
            name='description',
        ),
    ]
