# Generated by Django 3.1.5 on 2021-02-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0004_remove_sortfood_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('mealtype', models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=300)),
                ('calories', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fat', models.IntegerField()),
                ('fibre', models.IntegerField()),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SortFood',
        ),
    ]
