# Generated by Django 3.1.5 on 2021-03-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0005_auto_20210228_0024'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foodinfo',
        ),
    ]
