# Generated by Django 3.1.5 on 2021-03-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sort', '0005_delete_sortfood'),
        ('sort', '0006_delete_foodinfo'),
    ]

    operations = [
    ]
