# Generated by Django 3.1.5 on 2021-02-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodjournal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_choice', models.CharField(blank=True, choices=[('Sad', 'Sad'), ('Meh', 'Meh'), ('Happy', 'Happy')], max_length=10)),
                ('en_choice', models.CharField(blank=True, choices=[('Tired', 'Tired'), ('Meh', 'Meh'), ('Energetic', 'Energetic')], max_length=10)),
                ('hu_choice', models.CharField(blank=True, choices=[('Hungry', 'Hungry'), ('Meh', 'Meh'), ('Satisfied', 'Satisfied')], max_length=10)),
                ('st_choice', models.CharField(blank=True, choices=[('Stressed', 'Stressed'), ('Meh', 'Meh'), ('Calm', 'Calm')], max_length=10)),
                ('he_choice', models.CharField(blank=True, choices=[('Ill', 'Ill'), ('Meh', 'Meh'), ('Healthy', 'Healthy')], max_length=10)),
                ('journal', models.CharField(max_length=280)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
