# Generated by Django 3.1.5 on 2021-02-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodjournal', '0003_auto_20210214_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='happiness',
            field=models.CharField(blank=True, choices=[('Sad', 'Sad'), ('Mixed', 'Mixed'), ('Happy', 'Happy')], max_length=10),
        ),
    ]
