# Generated by Django 3.1.5 on 2021-02-15 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodjournal', '0005_auto_20210215_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='moodcolor',
        ),
    ]
