# Generated by Django 3.1.5 on 2021-02-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodjournal', '0006_remove_entry_moodcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='moodcolor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
