# Generated by Django 3.1.5 on 2021-02-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodjournal', '0007_entry_moodcolor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='stress',
            new_name='calmness',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='moodcolor',
        ),
    ]
