# Generated by Django 3.1.7 on 2021-02-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodjournal', '0008_auto_20210216_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
