# Generated by Django 3.1.4 on 2021-01-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210117_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='fibre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='protein',
            field=models.IntegerField(default=0),
        ),
    ]
