# Generated by Django 3.1.4 on 2021-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210117_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinfo',
            name='rawcook',
            field=models.CharField(default='test', max_length=300),
            preserve_default=False,
        ),
    ]
