# Generated by Django 3.1.4 on 2021-01-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_foodinfo_rawcook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodinfo',
            name='rawcook',
        ),
        migrations.AddField(
            model_name='foodinfo',
            name='mealtype',
            field=models.CharField(choices=[('BF', 'Breakfast'), ('LC', 'Lunch'), ('DN', 'Dinner')], default='test', max_length=300),
            preserve_default=False,
        ),
    ]
