# Generated by Django 3.1.4 on 2021-01-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20210117_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodinfo',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='mealtype',
            field=models.CharField(blank=True, choices=[('BF', 'Breakfast'), ('LC', 'Lunch'), ('DN', 'Dinner')], max_length=300),
        ),
    ]
