# Generated by Django 3.1.5 on 2021-02-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210117_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='mealtype',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=300),
        ),
    ]
