# Generated by Django 3.1.4 on 2021-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20210117_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinfo',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='carbs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='fat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='fibre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='mealtype',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=300),
        ),
        migrations.AlterField(
            model_name='foodinfo',
            name='protein',
            field=models.IntegerField(),
        ),
    ]
