# Generated by Django 3.1.7 on 2021-02-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20210208_2250'),
        ('database', '0007_auto_20210209_0120'),
    ]

    operations = [
    ]
