# Generated by Django 3.1.7 on 2021-02-25 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealmate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='food',
        ),
    ]
