# Generated by Django 3.1.5 on 2021-02-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='choosefood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mealtype', models.CharField(choices=[('BF', 'Breakfast'), ('LU', 'Lunch'), ('DR', 'Dinner')], default='', max_length=100)),
                ('calories', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('fibre', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
