# Generated by Django 3.1.4 on 2021-02-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choosefood',
        ),
    ]
